name = "Dmk"
uuid = "2e70eda1-e379-480b-be5f-6b294dd1451d"
authors = ["Timo Betcke <timo.betcke@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
StaticArrays = "1.9.13"
Test = "1.11.0"
TestItemRunner = "1.1.0"
TestItems = "1.0.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
